#!/usr/bin/env bash
# Author: Paige Duffin
# Read-backed phasing of all 46 samples, including all 10 Panama samples.
# Uses the complete samples.txt list generated by step 01.
# Inputs: per-sample BCFs from step 01, indexed BAMs, and the indexed combined
# A. cervicornis / S. fitti reference FASTA used for mapping.
# BAM names: {ID}.sorted.bam or {ID}_GATKd_sort.bam; provide one per sample.
# Software: WhatsHap and HTSlib (bgzip, tabix).
# Activate the WhatsHap environment before running, e.g.:
# conda activate whatshap-env
# USC HTSlib modules: ml gcc/13.3.0 openblas/0.3.28 htslib/1.19.1
# Usage: bash 02_whatshap_phase.sh [STEP01_OUTPUT_DIRECTORY] [BAM_DIRECTORY] [REFERENCE.fa] [NEW_OUTPUT_DIRECTORY]

set -euo pipefail

INPUT_DIR=${1:-whatshap_input}
BAM_DIR=${2:-input_bams}
REFERENCE=${3:-ref_genome_indexed/GCA_964034985.1_Acer_S.fitti.fa}
OUT_DIR=${4:-whatshap_phasing_output}
mkdir -- "$OUT_DIR"

while IFS= read -r SAMPLE; do
    # Accept either BAM naming convention used in the original workflow.
    BAMS=()
    for CANDIDATE in "$BAM_DIR/${SAMPLE}.sorted.bam" "$BAM_DIR/${SAMPLE}_GATKd_sort.bam"; do
        if [[ -f "$CANDIDATE" ]]; then
            BAMS+=("$CANDIDATE")
        fi
    done
    if [[ ${#BAMS[@]} -ne 1 ]]; then
        echo "Provide exactly one indexed BAM for $SAMPLE: ${SAMPLE}.sorted.bam or ${SAMPLE}_GATKd_sort.bam" >&2
        exit 1
    fi

    whatshap phase \
        -o "$OUT_DIR/${SAMPLE}_phased.pt1.vcf" \
        --reference "$REFERENCE" \
        --indels \
        "$INPUT_DIR/sep_by_samples/${SAMPLE}_for.phasing.bcf" \
        "${BAMS[0]}"

    # Compress and index each output for the subsequent 46-sample merge.
    bgzip -c "$OUT_DIR/${SAMPLE}_phased.pt1.vcf" \
        > "$OUT_DIR/${SAMPLE}_phased.pt1.vcf.gz"
    tabix -p vcf "$OUT_DIR/${SAMPLE}_phased.pt1.vcf.gz"
done < "$INPUT_DIR/samples.txt"
